name: 'Hello World'
description: 'Greet someone and record'
inputs:
  who-to-greet: #asdf
  description: 'Who to greet'
  required: true
  default: 'World'
outputs:
  time: # adsf
  description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
