on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: lyonk71/my-javascript-action@v1
      with:
        who-to-greet: 'Santa'
    - name: get the output time
      run: echo "the time was ${{ steps.hello.outputs.time }}"
